CREATE DATABASE IF NOT EXISTS colby;

USE colby;

CREATE TABLE IF NOT EXISTS media (
    id INT AUTO_INCREMENT PRIMARY KEY,
    node_id VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255) NOT NULL,
    src TEXT,
    position INT NOT NULL
);